version: '3'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file: ./docker-env/.env.pg
    volumes:
      # if you need persistent data, point data to local folder
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build:
      context: .
      target: dev-build
    restart: always
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  redis:
    image: 'redis:7.0-rc-alpine'
    restart: always
    command: sh -c "redis-server"
    ports:
      - '6379:6379'
    volumes:
      - '.:/var/lib/redis/data'
  sidekiq:
    build: .
    restart: always
    command: sh -c "bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - '.:/myapp'
    depends_on:
      - 'db'
      - 'redis'
    tty: true
    stdin_open: true
